version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      timezone: "Asia/Tokyo"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
