name: Detect build difference

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  check-build-difference:
    uses: natsukiyamada/explore_github/.github/workflows/detect_build_difference.yml@develop
