name: Caller Workflow

on:
  push:
    branches: [release, develop]
  pull_request:
    branches: [release, develop]

jobs:
  call-basic-ci:
    uses: natsukiyamada/explore_github/.github/workflows/main.yml@main
