name: Deploy on PR Merged to Develop

on:
  pull_request:
    branches: [develop]
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Upload to kintone
        run: |
          npx kintone-customize-uploader dest/customize-manifest.json --base-url $KINTONE_BASE_URL --username $KINTONE_USERNAME --password $KINTONE_PASSWORD
        env:
          KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
          KINTONE_USERNAME: ${{ secrets.KINTONE_USERNAME }}
          KINTONE_PASSWORD: ${{ secrets.KINTONE_PASSWORD }}